spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret_key: ${SECRET_KEY}
  access_exp: ${ACCESS_EXP}

cloud:
  aws:
    credentials:
      access_key: ${S3_ACCESS_KEY}
      secret_key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error